# name: Daily Verse Job

# on:
#   schedule:
#     # 7:00 PM IST = 13:30 UTC
#     - cron: "30 13 * * *"
#   workflow_dispatch:

# jobs:
#   run-main:
#     runs-on: ubuntu-latest
#     timeout-minutes: 20

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run daily pipeline
#         env:
#           DB_URI: ${{ secrets.DB_URI }}
#           llm_api_key: ${{ secrets.LLM_API_KEY }}
#           freepik_api_key: ${{ secrets.FREEPIK_API_KEY }}
#         run: python main.py
